"use client";
import { useMemo,useState } from "react";
import type { RegisterRow } from "@/lib/types";
const displayDate=(v:string)=>new Intl.DateTimeFormat("en-GB").format(new Date(v));
const perPage=20;
export default function RegisterTable({rows}:{rows:RegisterRow[]}){const [search,setSearch]=useState("");const [result,setResult]=useState("");const [tester,setTester]=useState("");const [location,setLocation]=useState("");const [due,setDue]=useState("");const [sort,setSort]=useState<keyof RegisterRow>("assetNumber");const [asc,setAsc]=useState(true);const [page,setPage]=useState(1);
 const filtered=useMemo(()=>rows.filter(r=>(!search||`${r.assetNumber} ${r.assetName}`.toLowerCase().includes(search.toLowerCase()))&&(!result||r.result===result)&&(!tester||r.tester===tester)&&(!location||(r.location||"").toLowerCase().includes(location.toLowerCase()))&&(!due||r.nextDueDate<=due)).sort((a,b)=>String(a[sort]??"").localeCompare(String(b[sort]??""))*(asc?1:-1)),[rows,search,result,tester,location,due,sort,asc]);
 const pages=Math.max(1,Math.ceil(filtered.length/perPage));const shown=filtered.slice((Math.min(page,pages)-1)*perPage,Math.min(page,pages)*perPage);const testers=[...new Set(rows.map(r=>r.tester))];
 function order(key:keyof RegisterRow){if(sort===key)setAsc(!asc);else{setSort(key);setAsc(true)}}
 const exportUrl="/api/export?"+new URLSearchParams({scope:"current",search,result,tester,location,due,sort:String(sort),dir:asc?"asc":"desc"});
 return <><div className="filters"><input aria-label="Search asset" placeholder="Search asset number or name" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/><select aria-label="Result" value={result} onChange={e=>{setResult(e.target.value);setPage(1)}}><option value="">All results</option><option>PASS</option><option>FAIL</option></select><select aria-label="Tester" value={tester} onChange={e=>{setTester(e.target.value);setPage(1)}}><option value="">All testers</option>{testers.map(v=><option key={v}>{v}</option>)}</select><input aria-label="Location" placeholder="Location" value={location} onChange={e=>{setLocation(e.target.value);setPage(1)}}/><input aria-label="Due by" type="date" value={due} onChange={e=>{setDue(e.target.value);setPage(1)}}/></div><p><a className="button" href={exportUrl}>Export filtered view</a> <span className="muted">{filtered.length} asset{filtered.length===1?"":"s"}</span></p><div className="table-wrap"><table><thead><tr>{([["assetNumber","Asset Number"],["assetName","Asset Name"],["serial","Serial"],["location","Location"],["testDate","Last Test"],["result","Result"],["tester","Tester"],["nextDueDate","Next Due"],["status","Status"],["notes","Notes"]] as [keyof RegisterRow,string][]).map(([key,label])=><th key={key}><button onClick={()=>order(key)}>{label}{sort===key?(asc?" ↑":" ↓"):""}</button></th>)}</tr></thead><tbody>{shown.length?shown.map(r=><tr key={r.id}><td>{r.assetNumber}</td><td>{r.assetName}</td><td>{r.serial||"—"}</td><td>{r.location||"—"}</td><td>{displayDate(r.testDate)}</td><td>{r.result}</td><td>{r.tester}</td><td>{displayDate(r.nextDueDate)}</td><td><span className={`badge ${r.status.toLowerCase().replace(" ","-")}`}>{r.status}</span></td><td>{r.notes||"—"}</td></tr>):<tr><td colSpan={10}>No matching PAT records.</td></tr>}</tbody></table></div><div className="pagination"><button className="secondary" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {Math.min(page,pages)} of {pages}</span><button className="secondary" disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Next</button></div></>}
